source "https://rubygems.org"

gem 'sinatra', require: 'sinatra'
gem 'rack', '~> 1.4.2'
gem 'mongoid', '~> 3.0.0'
gem 'rack-flash3', require: 'rack-flash'
gem 'pry'
gem 'alipay'
gem 'redis-rack', '~> 1.4.2', require: 'rack/session/redis'
gem 'carrierwave'
gem 'carrierwave-mongoid', require: 'carrierwave/mongoid'
gem 'actionmailer', require: 'action_mailer'
gem 'mongoid_paginate'
gem 'clockwork'
gem 'redis'
gem 'carrierwave-ftp'
gem 'puma'
